### ISSUE TITLE
require('mongoose') fails to load

### ISSUE THREAD

**Issue by ksylvan** [sergeyksv/tungus#14]
node version: v0.12.7
npm: 2.11.3

After "npm install --save tungus" and "npm install --save mongoose" in a clean directory.

```
# ls node_modules/
mongoose  tungus
```

Then I run node:

```
# node
> var tungus = require('tungus');
undefined
> var mongoose = require('mongoose')
Error: Cannot find module './/tmp/clean/node_modules/tungus/driver'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/tmp/clean/node_modules/mongoose/lib/drivers/index.js:8:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Not sure why mongoose is looking for .//tmp/clean/... instead of /tmp/clean since the driver is there:

```
/tmp/clean# ls node_modules/tungus/driver/
binary.js  collection.js  connection.js  objectid.js  tingodb.js
```

Any help appreciated. Thank you!

**Comment by weeman1337** [comment]
Same for me
mongoose 4.0.8

**Comment by castrolol** [comment]
I get the same error

**Comment by derozgurg** [comment]
same error

**Comment by sergeyksv** [comment]
This is bug of 4.0.x mongoose which is fixed in 4.1. Howether 4.x version is not supported currently because of migration to API of mongodb driver 2.x

**Comment by ReneHollander** [comment]
I also get the same problem using mongoose 4.1.10

**Comment by ReneHollander** [comment]
I just realized that that tungus is not yet compativle to 4.x. I switched to 3.x for now again.

**Comment by ksylvan** [comment]
Closing as dup of https://github.com/sergeyksv/tungus/issues/15 - Also this repo seems inactive.
